### ISSUE TITLE
Unable to find a specification

### ISSUE THREAD

**Issue by chiragpurohit71085** [google/promises#69]
I am trying to install this with cocoapods

I first set (as per doc) in my podfile,

pod 'PromisesObjC', '~> 1.2.3'

it gave me following error

Unable to find a specification for `PromisesObjC (~> 1.2.3)`

Then I tried with pod 'PromisesObjC'

it gave me following error

Unable to find a specification for `PromisesObjC`

I am using xcode 9.4

**Comment by chiragpurohit71085** [comment]
thanks, let me share my pod file snippet in a while.

**Comment by chiragpurohit71085** [comment]
`target 'xxxx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XXX
    
	pod  'Firebase/Core'
	pod  'Firebase/Auth'
    pod  'Firebase/Database'
    pod  'Firebase/Storage'
    pod  'Firebase/Analytics'
    pod  'Firebase/Messaging'
    pod  'Firebase/Crash'
    pod  'Firebase/DynamicLinks'
    pod  'SDWebImage', '~>3.8'
    pod  'GoogleSignIn'
    pod  'FBSDKLoginKit'
    pod  'FBSDKShareKit'
    pod  'ECSlidingViewController', '~> 2.0.3'
    pod  'MBProgressHUD', '~> 0.9.2'
    pod  'JTSImageViewController', '1.5.1'
    pod  'IQKeyboardManager'
    pod 'AFNetworking', '~> 3.0'
    pod 'GooglePlaces'
    pod 'PureLayout'
    pod 'Branch'
    pod  'AccountKit'
    pod 'Fabric'
    pod 'Crashlytics'
	pod 'Appsee'
	pod 'TwitterKit'
	pod 'PromisesObjC'
	pod 'RKTagsView'


end`

**Comment by chiragpurohit71085** [comment]
I have 

 cocoapods-1.5.3

**Comment by shoumikhin** [comment]
I'm using the same version and just ran it on your `Podfile`:

```sh
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.2.1)
Installing AccountKit (4.35.0)
Installing Appsee (2.4.3)
Installing Bolts (1.9.0)
Installing Branch (0.25.3)
Installing Crashlytics (3.10.7)
Installing ECSlidingViewController (2.0.3)
Installing FBSDKCoreKit (4.35.0)
Installing FBSDKLoginKit (4.35.0)
Installing FBSDKShareKit (4.35.0)
Installing Fabric (1.7.11)
Installing Firebase (5.6.0)
Installing FirebaseAnalytics (5.1.1)
Installing FirebaseAuth (5.0.3)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (5.1.1)
Installing FirebaseCrash (3.1.1)
Installing FirebaseDatabase (5.0.2)
Installing FirebaseDynamicLinks (3.0.2)
Installing FirebaseInstanceID (3.2.1)
Installing FirebaseMessaging (3.1.0)
Installing FirebaseStorage (3.0.0)
Installing GTMOAuth2 (1.1.6)
Installing GTMSessionFetcher (1.2.0)
Installing GoogleAppMeasurement (5.1.1)
Installing GoogleMaps (2.7.0)
Installing GooglePlaces (2.7.0)
Installing GoogleSignIn (4.2.0)
Installing GoogleToolboxForMac (2.1.4)
Installing GoogleUtilities (5.2.2)
Installing IQKeyboardManager (6.1.1)
Installing JTSImageViewController (1.5.1)
Installing MBProgressHUD (0.9.2)
Installing PromisesObjC (1.2.3)
Installing Protobuf (3.6.1)
Installing PureLayout (3.1)
Installing RKTagsView (1.4.0)
Installing SDWebImage (3.8.2)
Installing TwitterCore (3.2.0)
Installing TwitterKit (3.4.0)
Installing leveldb-library (1.20)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 27 dependencies from the Podfile and 42 total pods installed.
```

**Comment by chiragpurohit71085** [comment]
hmm which xcode version you are using? or this should not affected by that? I am using xcode 9.4

**Comment by shoumikhin** [comment]
Same Xcode version, it shouldn't matter.
Try `pod install --verbose`, maybe you'd spot something interesting.

**Comment by chiragpurohit71085** [comment]
here is the output

pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-XXXX`: (``)

Finding Podfile changes
  A PromisesObjC
  - AFNetworking
  - AccountKit
  - Appsee
  - Branch
  - Crashlytics
  - ECSlidingViewController
  - FBSDKLoginKit
  - FBSDKShareKit
  - Fabric
  - Firebase
  - GooglePlaces
  - GoogleSignIn
  - IQKeyboardManager
  - JTSImageViewController
  - MBProgressHUD
  - PureLayout
  - RKTagsView
  - SDWebImage
  - TwitterKit

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `PromisesObjC (~> 1.2.3)`

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

[!] Automatically assigning platform `ios` with version `10.0` on target `XXXX` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`

**Comment by shoumikhin** [comment]
I believe something is broken with your CocoaPods setup.
Wonder if the following could help:

```sh
pod repo remove master
pod setup
pod install
```

**Comment by chiragpurohit71085** [comment]
okay, let me try this and get back to you
